export const articlesContent = [
  {
    slug: 'cash-calls',
    title: 'Cash Calls',
    author: 'Kody Carroll, President, Integrity Audit and Accounting Ltd.',
    content:
      <>
        <h5>Protocol, Practice and Problems</h5>
        <p>When I sent out an open call for readers to suggest an operational accounting topic to write about, the response was overwhelmingly in favour of one topic: cash calls.</p>
        <p>To begin, why do we have cash calls in industry? In essence, the Operator isn’t supposed to make money over the Non-Operators just by virtue of their role as Operator, but they aren’t supposed to lose money either. The financing costs of capital projects are a very real expenditure and carry a significant burden to an Operator when the amounts involved get high enough. If an Operator has paid cash to the vendors involved in a capital project but they don’t receive the Joint-Operators’ (Non-Operators’) share of the expenditures until a couple of months later, then the Operator has incurred a financing cost associated with carrying the Joint-Operators’ interests.</p>
        <p>It is not surprising that both Operators and Non-Operators are wrestling with cash calls. Almost every JV Accountant in the Canadian oil and gas industry has run into a cash call problem whether it is a collection, reporting, management, or reconciliation issue. How should cash calls be administered? What do the agreements say about them? What is industry actually doing in practice? How do we resolve the problems that pop up? These are going to be the questions that we try to answer as we address the three Ps of cash calls: Protocol, Practice and Problems.</p>
        <h5>Cash Call Protocol – The Agreements</h5>
        <p>Ultimately, it is either the governing Joint Operating Agreement (JOA) or the Accounting Procedure attached to the JOA that discusses the protocol of cash call management. While the cash call clauses in the operating procedures and accounting procedures mostly say the same thing, I have seen a couple of (older) agreements here and there that have some unique phrasing or are silent on cash advances altogether. Therein lies the first step of cash call management – understand the terms of the particular Agreement governing your property.</p>
        <p>For the purpose of this blog, let’s review just the terms of the Canadian energy industry’s most prevalent procedures, the 1990 CAPL Operating Procedure and the 1996 PASC Accounting Procedure that is typically attached to it. The clauses that are going to interest us are Clauses 503(b) and (c) (Advance of Costs) of CAPL 1990, and Clause 104 (Capital Advances) of PASC 1996.</p>
        <p>In a nutshell, here’s what our industry protocol is supposed to be for cash call invoicing, payment, and reimbursement:</p>
        <p>1) The Operator is to provide a written estimate of capital expenditures that are expected to be paid for a project for one month, which is the basis of the cash call invoice to the Non-Operator (i.e. Joint Operator). The Operator must send this estimate to the Non-Operator no earlier than 30 days before the start of the month the cash call applies to.</p>
        <p>Let’s use capital expenditures for the month of May for an example. The Operator should submit May’s cash call estimate (and invoice) to the Non-Operators no earlier than April 1st (30 days before May 1st). Please note that the estimate is only to include the capital expenditures that are to be paid in the month of May and not just incurred or booked in May. An Operator may book an item in May but have payment terms of 60 days, in which case the expenditure should appear on the July cash call invoice.</p>
        <p>2) The Non-Operator must pay the Operator’s cash call invoice either 20 days after receipt of the invoice, or on the 15th of the month that the estimate relates, whichever is later.</p>
        <p>In this case, let’s say the Operator submitted the cash call invoice right on April 1st. The Non-Operator has until the latter of April 20th (20 days) or May 15th to pay that invoice. If the Operator waits until April 30th to submit the invoice, then the Non-Operator has until the latter of May 15th and May 20th to pay it.</p>
        <p>3) The Operator spins off his JVB to the Non-Operator, and adjusts the amount owing for capital on the project in question (either manually or systematically) to reflect the advance.</p>
        <p>Let’s say the May JVB spins off, which will likely be in early June some time. Hopefully the Operator has had time to book the advance and hopefully the Non-Operator has paid their invoice on time. If either of those conditions isn’t satisfied, we’re already going straight into a reconciliation effort, but let’s keep going anyway.</p>
        <p>4) If the month’s actual capital expenditures are over the amount of that month’s cash call when the JVBs spin off, then the Non-Operator is required to pay the shortfall within 30 days pursuant to Clause 103 of PASC 1996. If there is an excess, however, then the Operator must refund it on the JVB to which it pertains. If the Operator doesn’t refund it, then the Non-Operator gets to charge interest to the Operator according to Clause 106.</p>
        <p>Of note, Clause 503 of CAPL 2007 was changed slightly to suggest that the Operator may either apply the excess to the following month’s cash call or refund the difference.</p>
        <p>5) For the next month, go back to step 1 and repeat the cycle until the end of the project.</p>
        <p>The cash call clauses in CAPL 1990 and PASC 1996 largely say the same thing and are very complementary to each other. However, PASC 1996 has one additional detail that deserves attention. Clause 104 of PASC 1996 indicates that the Operator must submit to the Non-Operator a “reasonably detailed estimate of the costs proposed to be paid”. I would suggest that this means the Operator needs to break the cost estimate down to a major account level at the very least. It is true that the terms of CAPL will supersede PASC in the event of a discrepancy between the two, however this additional phrasing from PASC does not constitute a discrepancy but rather an additional requirement.</p>
        <p>That was easy, wasn’t it?</p>
        <h5>Cash Call Practice – The “Industry Method”</h5>
        <p>No, unfortunately the protocol specified in the agreements wasn’t easy at all. It is cumbersome to manage, difficult to implement, and administratively problematic. Hence, some companies started developing their own cash call practices and before long, everyone followed suit. Let’s call this the “Industry Method”, and we’ll break this procedure into some steps as we did above.</p>
        <p>1) The Operator invoices the Non-Operators for the full amount of an AFE well in advance.</p>
        <p>2) The Non-Operators may or may not pay the invoice.</p>
        <p>3) If the invoice is paid, the Operator releases a JVB that systematically draws down the current month’s capital expenditures against the cash call balance.</p>
        <p>4) Any shortfall over the full project cash call gets invoiced to the Non-Operator on the JVB, or the Operator hangs on to any excess in their subledgers until such time that a Non-Operator has done all of their reconciling and starts making phone calls to recover the balance.</p>
        <p>5) The Operator and the Non-Operator argue over what the actual balance left over is.</p>
        <p>Let’s be very clear. The above Industry Method is not as per the model agreements, yet many think that it is just because this process is so prevalent throughout the industry.</p>
        <h5>Cash Call Problems</h5>
        <p>a) Protocol Versus Practice</p>
        <p>Let’s face it; MOST (notice the emphasis on most) companies aren’t able to adhere to the terms of the governing Agreement when it comes to cash calls. We’ve become a remarkably efficient industry as far as our use of technology and workflow systems, but when we’re doing more with fewer resources, it becomes less realistic to think that two companies will be able to manage the cash calls on a monthly basis within the tight timeframes specified in the agreements. Throw in the fact that there are disputes or reversals/corrections along the way, and the problem compounds. One thought process is that companies can just keep rolling balances and payments forward until the end of the project in an effort to take total cash calls paid less total capital expenditures to reach a balance owed one way or another, but the number of transactions involved has greatly complicated our reconciliations.</p>
        <p>Another issue is that the cash call invoices are to be based on amounts paid for the Joint Account, but the JVBs are issued based on the accounting period in which the original invoice is booked. Most companies in industry don’t have zero day payment terms, so is the Operator really out the cash and is there a need to cash call in the first place?</p>
        <p>The Industry Method resolves some problems as far as making cash calls somewhat administratively easier to manage, but it creates other problems as far as companies’ cash management goes. If you’re working with a major international oil and gas corporation, a $1MM cash call invoice is a drop in a bucket and that cash won’t make or break the company (especially if they’re similarly invoicing their Non-Operators for the full amount of a project).</p>
        <p>Small companies, however, may have very tight cash flow and can be significantly impeded by an Operator’s demand for a large sum of cash up front. So what happens if the Non-Operator refuses to pay a cash call invoice?</p>
        <p>b) Refusal To Pay a Cash Call</p>
        <p>While the agreements don’t allow for it, it happens where an Operator will withhold information because a single cash call invoice (for the Non-Operators full share of the AFE) hasn’t been paid. The issue will involve a number of employees, then it will involve supervisors, then managers, then vice presidents – each individual that gets involved as we move our way up the corporate ladder increases the administrative cost associated with cash call management, perhaps even beyond the financing costs of the capital being cash called for.</p>
        <p>At the end of the day, there is one simple reality that should guide our cash call management. Both parties have signed their name to a governing Agreement. Has the Operator invoiced their cash call in accordance with this Agreement or not? If the Operator has chosen the Industry Method and invoices the entire cost of a project well in advance and expects immediate payment, then a Non-Operator has every right to refuse payment of the cash call invoice. Operators that haven’t invoiced their cash calls according to the agreements they’ve signed need to be wary before taking action like withholding information or threatening to declare a party in penalty.</p>
        <p>Non-Operators beware; this is not a ticket to start refusing payment on all of your cash call invoices. There might be some other considerations at hand.</p>
        <p>First, what is your company’s own practice for invoicing out cash calls? It only makes sense to manage incoming cash call invoices the same way you manage outgoing ones, lest you start having your Non-Operators refuse payment of your cash call invoices.</p>
        <p>Second, has the Operator made a reasonable argument that the project will be done within one month, that they are expecting the majority of the costs to be incurred in that first month and therefore have only cash called for that first month’s costs? If they have, then they are adhering to the terms of the Agreement (provided their invoice timing is as indicated above) even though they have chosen to only send the first month’s cash call invoice.</p>
        <p>Third, are you, as a Non-Operator, organized well enough and have the resources available to accommodate the administrative difficulty that will ensue if the Operator happens to agree that they will cash call according to the specific terms of the Agreement. I’m familiar with some Operators in this industry that ARE organized enough to manage their cash calls according to CAPL 1990 and PASC 1996, but have chosen the Industry Method for simplicity and to ease the administrative burden. If cash flow is an issue, then you won’t need to pay a cash call invoice for an entire project at the start, but be prepared to pay more for administrative time, bookkeeping and reconciliation along the way if the Operator instead chooses to do things by the book.</p>
        <p>Finally, as a word of caution to organizations whose policy is to not pay cash calls, please note that your company’s policy does not supersede the governing Agreements.</p>
        <h5>Cash Call Reconciliation</h5>
        <p>Let’s say we pass the first hurdle of the initial administration and payment, and the two companies have agreed on how a cash call will be paid (one way or another). The project goes forward, costs are incurred, and the cash call balances are drawn down. Hopefully both parties have been doing monthly cash call reconciliations along the way and have done timely reversals to make things easier, but this doesn’t always happen.</p>
        <p>Quite often, the Non-Operator will make a phone call to the Operator well after the end of a project to ask for reimbursement on a cash call. The parties find that the Operator’s and Non-Operator’s cash call balances don’t match, or perhaps the Operator doesn’t show a left over cash call payable balance at all. The discrepancy typically occurs because of disputes on JIBLink whereby the Non-Operator has only drawn down amounts that have been accepted, but the Operator has drawn down amounts that have been billed. If there are no disputes, then are there JVBs circulating in the workflow systems that have not been booked to the Accounting System? Has something been booked to A/P rather than to the cash call receivable account as a cash call draw down?</p>
        <p>When it comes to a Non-Operator’s cash call reconciliation, I would suggest that you make sure you’re not just reconciling balances against your own books for financial reporting purposes on a monthly basis, but rather also reconcile against the Operator’s cash call balances on the JVBs on a monthly basis. It will make it far easier to see where there are discrepancies along the ways and what they are.</p>
        <p>For Operators, I would strongly suggest that this is yet another reason to do reversals through a DOI rather than reversing something directly from a subledger account to another general ledger account. The Non-Operator won’t be able to tell that you’ve reversed an item or changed their cash call balance when you do this type of reversal entry directly against the subledgers. If you do it through a DOI, the accounting system will usually do the rest of the work for you, the Non-Operator clearly sees what you’ve done, and there’s no need to spend excessive time on cash call reconciliation at the end of the day.</p>
        <h5>PASC 2011 – Improvements to the Cash Call Process</h5>
        <p>In my first blog on the new Board approved 2011 PASC Accounting Procedure, I discussed a few of the changes that were made to the cash call clause in PASC 2011. To reiterate, PASC wasn’t able to write our existing practice into the new Accounting Procedure because they realized the impact this would have on smaller companies that may struggle with cash flow. They did, however, try to ease the burden by writing in some additional procedure that may work even if you’re using the 1996 PASC Accounting Procedure.</p>
        <p>Instead of monthly statements, the Operator now only provides a schedule showing all anticipated payments for the entire project by month, and the Non-Operator may elect to pay either according to the Operator’s schedule or the full amount of the cash call. This eases the burden on both parties slightly by allowing the Operator to provide only one statement in advance (rather than one statement every month), and also by allowing the Non-Operator to book all of their cash calls in future accounting periods at once, eliminating the need for monthly cash call invoice management. There will still be some increased reconciliation effort along the way if the Non-Operator chooses to not pay the full amount in advance, but at least we’re getting closer to something manageable.</p>
        <h5>Closing</h5>
        <p>If you’re reading this blog, you’re likely having a specific cash call issue and are working to resolve it. You’re not alone. There are few companies in industry where cash calls haven’t been a problem at some point in time.</p>
        <p>One of Integrity’s goals in creating these blogs is to help Operators and Non-Operators alike resolve their issues and find common ground by providing opinion on interpretation. Hopefully, this blog has provided some guidance on what the governing agreements say and at least why the cash call issues you’re experiencing are appearing in the first place.</p>
        <p>If your cash call issues persist after reviewing the information contained in this blog, then I might also suggest that you refer to Clause 503(a) of CAPL 1990, which describes how Operators have the option of requiring a letter of credit from the Non-Operator’s bank. This might not help you with your current cash call issue at hand, but it will at least be a consideration for future dealings.</p>
        <p>Cash calls will unfortunately continue to be a problem in industry, but to resolve the three Ps of cash calls, I would like to propose the three Cs of cash call resolution: communication, compromise and coordination. Communicate with your counterparts, compromise to reach something that works for everyone, and coordinate your reconciliations with your partners.</p>
        <p>If you have any questions on the subject matter contained within this blog or would like additional information on cash calls or other joint venture issues, please feel free contact us through our website at www.integrity-audit.com.</p>
        <p><i>All content provided on this blog is for informational purposes only. The content contained herein does not represent the official or unofficial opinion of PASC, CAPL or any other industry association and is based solely on the opinion of the author. The owner of this blog makes no representations as to the accuracy or completeness of any information on this site or found by following any link on this site. The owner will not be liable for any errors or omissions in this information nor for the availability of this information. The owner will not be liable for any losses, injuries, or damages from the display or use of this information.</i></p>
      </>
  },
  {
    slug: 'pasc-2011-accounting-procedure-opinion-and-commentary',
    title: 'PASC 2011 Accounting Procedure: Opinion and Commentary',
    author: 'Kody Carroll, President, Integrity Audit and Accounting Ltd.',
    content:
      <>
        <p>I recently found an old binder in my office bookcase labelled “Proposed PASC 2006”. I was part of a team that was providing some “industry comment” back to PASC at the time. Out of curiosity, I started flipping through the pages and quickly realized that very little of that document survived to the PASC 2011 Accounting Procedure. In fact, PASC 2011 looked to have been completely re-written.</p>
        <p>The reason I mention this is to highlight the challenges that PASC had in developing a new Accounting Procedure. While it’s easy to look at the final version and criticize how certain items were handled, I’m sure it was difficult for the members of the JIRC (Joint Interest Research Committee) to carefully debate and modify each and every clause for any conceivable scenario, and to add in new phrasing to address items that weren’t issues back when PASC 1996 was drafted. As I mentioned in Part 1 of this blog series, my hat is off to those that volunteered and had involvement in such a large task.</p>
        <p>All in all, how do we summarize the key take-a-ways when it comes to the PASC 2011 Accounting Procedure?</p>
        <h5>Making Accountants of Engineers</h5>
        <p>The Accounting Procedure is not just a document for accountants and auditors. Now more than ever, the engineers that are preparing the AFE budgets and operating forecasts need to be aware of what the terms of the PASC 2011 Accounting Procedure are saying. The budgets and forecasts are no longer just for information and cost control, but are now approval mechanisms and documents against which charges to the Joint Account will be audited. In reading through PASC 2011 and subsequently preparing AFE budgets and operating cost forecasts, I would encourage readers to keep in mind that the terms of the Accounting Procedure don’t just apply to direct charges or directly charged internal labour, but also to any amounts that arise because of internal system generated allocation processes. Also, given some of the changes affecting our industry (like EPAP for example), there might be some project-based items that are worth discussion amongst Joint-Owners where it comes to cost sharing.</p>
        <h5>To Seek Permission or Ask Forgiveness?</h5>
        <p>A good joint venture auditor looks far beyond just coding errors, and ultimately looks towards the governing Accounting Procedure (and now therefore an AFE or approved cost forecast) to establish the eligibility of any item. In any Accounting Procedure, anything is chargeable – as long as you get approval. In PASC 1996 (and its predecessors), “Approval” was as per Clause 110, which essentially says that Owners will receive something in writing and they have to vote on it within 15 days. This sounds like a lot of work, though, if you’re just trying to get approval for one offsite professional consultant who was working on a job for a few days. An auditor comes along two years later, smiles and says, “Did you get approval for this charge? No? Oh, then it’s covered by your overhead.”</p>
        <p>The new Accounting Procedure makes “Approval” a far easier process, but it’s very important for companies to take advantage of this by not hiding behind any vague cost categories on the AFEs or operating cost forecasts. I readily expect auditors to challenge situations where the AFE cost estimate does not contain sufficient detail to demonstrate that approval really has been given. Just as an example, I might suggest that more detailed descriptions like “Offsite Technical Consulting”, “Contract Off-Site Professional Consulting” and “Second Level Supervision” will need to work their way into AFE cost estimates. In my opinion, vague description like “Consulting” or “Supervision” will not be sufficient to grant approval through an AFE.</p>
        <h5>Implementing the Accounting Procedure</h5>
        <p>As far as an industry goes, it took quite a while for everyone to generally accept PASC 1996, and PASC 1996 was more or less just an expansion of the same type of organization that was in its predecessor, PASC 1988. I imagine it will take just as long, if not longer, for PASC 2011 to become our new “industry standard” document.</p>
        <p>It will take time for industry’s Joint Venture Representatives to get comfortable enough with the PASC 2011 Accounting Procedure to start attaching it to all of their Joint Operating Agreements (JOAs). This will provide the rest of us with an opportunity to ensure that our systems and internal procedures are equipped to accommodate the changes incorporated into the Accounting Procedure, particularly as it relates to overhead. On the topic of overhead, I have never seen or heard about any kind of independent Canadian study that showed how our “industry standard” overhead recovery rates compare to the actual corporate G&amp;A costs attributable to joint operations. The Operator is not supposed to profit from their role as Operator, but they’re not supposed to lose money out of it either. With the flexibility now offered by Article III of PASC 2011 (including options that increase capital overhead), and the ability to pick and choose rates for a variety of operating activities, it would be interesting to see such an industry study and compare it to the alternatives provided by PASC.</p>
        <h5>Getting PASC 2011</h5>
        <p>At this point I think it’s important to note that use of PASC 2011 is not free, unlike PASC 1996, and so I would encourage readers to take a look at the PASC website for the licensing options. In a nutshell, the licensing ranges from $200.00 to $2,000.00 per year, depending on how many of your agreements have PASC 2011 as the accounting procedure. PASC members were mailed a reference-only copy of PASC 2011 back in January 2012, but members may purchase additional reference copies from the PASC website at a cost of $55.00 per copy.</p>
        <h5>Closing – A Matter of Opinion</h5>
        <p>PASC 2011 offers a lot of improvements over its predecessors, but you will never find a document that is ideal for every company in the industry. Since I started this blog series, I’ve had a few people ask me, “So do you think I should start using PASC 2011?” PASC certainly hopes you do. My answer to these individuals was, “It depends”. It will depend on your management and administrative practices, your company size, your field organization, your allocation procedures, your area of operations, and of course whether you’re the Operator or Non-Operator; all of these are things to consider when you’re reviewing PASC 2011 and deciding whether to adopt it or not.</p>
        <p>I’ve heard a fair number of comments that the PASC 2011 Accounting Procedure is the best accounting document industry has seen come along, and I’d be inclined to agree. What we have in PASC 2011 is a re-write with more clear terms and a layout that is easier to follow in some cases, but also some deliberately vague open doors that we as an industry will have to interpret. The Accounting Procedure Interpretation (API) documents provide excellent guidance on previously contentious topics by giving us clear and specific direction on what it an allowable charge to the Joint Account, especially where it comes to Engineering activities. The Accounting Procedure itself has been restructured and reorganized to accommodate the elimination of the Explanatory Texts which means we don’t need to search in multiple places to understand what’s allowable and what not.  There are still a couple of kinks to work out in PASC 2011, so it might also be worthwhile to monitor the PASC discussion boards (which are open to both PASC members and non-members) to see what kinds of questions are popping up.</p>
        <p>If you have any questions on the subject matter contained within this blog or are interested in a custom training program for your company on joint venture issues, please feel free contact us through our website at www.integrity-audit.com. To recommend topics for future blogs, please feel free to email us at info@integrity-audit.com.</p>
        <p><i>All content provided on this blog is for informational purposes only. The content contained herein does not represent the official or unofficial opinion of PASC, CAPL or any other industry association and is based solely on the opinion of the author. The owner of this blog makes no representations as to the accuracy or completeness of any information on this site or found by following any link on this site. The owner will not be liable for any errors or omissions in this information nor for the availability of this information. The owner will not be liable for any losses, injuries, or damages from the display or use of this information.</i></p>
      </>
  },
  {
    slug: 'pasc-2011-accounting-procedure-overhead-and-administration',
    title: 'PASC 2011 Accounting Procedure: Overhead and Administration',
    author: 'Kody Carroll, President, Integrity Audit and Accounting Ltd.',
    content:
      <>
        <p>The challenge of preparing an overhead discussion isn’t just to describe the process of how to charge it. That’s pretty easy; most companies’ systems already have built in processes that do it for you. The challenge comes with deciding what constitutes “administration”, and therefore determining what overhead does or does not cover.</p>
        <p>This third blog in my series on the PASC 2011 Accounting Procedure first tries to address some of the discussion around administration costs and fees, and then reviews some of the changes to Article III on Overhead.</p>
        <h5>What is Overhead?</h5>
        <p>For all intents and purposes, overhead is supposed to cover everything that is not directly chargeable in Article II. Sounds simple, but quite often it isn’t. PASC 2011 has provided significantly more guidance on what should be considered administration than its predecessors by adding a greatly expanded definition of “Administration” and through some more specific phrasing in Article II, but there is still likely going to be some gray areas here and there. PASC 2011 doesn’t have anything like “The Grid” that was attached to the PASC 1996 Accounting Procedure (the PASC 2011 pre-amble discusses why the grid was removed), so it was of course necessary to expand on what is covered by overhead in the text of PASC 2011.</p>
        <p>While we have more direction on which of the Operator-provided functions are to be considered overhead, we can still anticipate more discussion around the chargeability of contracted administrative services or third party administration fees.</p>
        <h5>Third Party Administration</h5>
        <p>Third party administration costs can take many different forms and might imply different things to different people. For example, they may be established in a custom processing or contract operating arrangement as a fixed fee, they may arise on vendors’ invoices as a surcharge, or there might be specific administrative activities identifiable on something like an engineering firm’s invoice. What I can say in general about PASC 2011 is that a third party’s administrative costs that support an allowable contracted service are chargeable to the Joint Account. However, if the contracted service itself is an administrative activity, it remains not chargeable.</p>
        <p>I recently attended a PJVA early morning session titled “We Only Want Custom Processing!” In essence, the peer discussion was on whether Non-Operators should accept the third party administration/production accounting fees that often accompany contract operating or custom processing agreements. The only general consensus that I saw there was “Do unto others as you would have them do unto you,” but otherwise there was no unanimous opinion on whether these charges should be universally accepted or not.</p>
        <p>Auditors like to use a certain phrase from Clause 207(a) of the PASC 1996 Accounting Procedure Explanatory Text (and similar phrasing also exists in PASC 1988): “Contracted services normally considered overhead shall not be charged to the Joint Account.” It is often the case that an auditor will use this clause to raise an exception if they see something that looks to be administrative in nature or would be something normally done by the Operator in-house, even if it is from a contract operating or custom processing scenario.</p>
        <p>PASC 2011 added some more clarification in Clause 207 by indicating that the Operator may charge for the “…cost of associated reporting performed by the contract operator if required under a contract operating arrangement.” In other words, involuntary production accounting fees would be chargeable to the Joint Account, which is in line with suggestions offered by some of the members of the audit community at the PJVA early morning session. Some custom processing arrangements require that a producer hand production accounting over to the custom processor and a fee must be charged for this service if the processor wants to go through that facility. This is one example of a situation where I would suggest that the production accounting fee would be chargeable to the Joint Account.</p>
        <p>I’d like to offer one more point with respect to the administration/production accounting fees that are charged on contract operating agreements, and I’m certain that this has already been contemplated by a number of readers of this blog. Is there anything preventing a company from agreeing to a $1,000 all-in contract operating fee, rather than a $750 contract operating fee plus a $250 administration fee? If this is the case, it becomes very difficult for an auditor to scrutinize and challenge any administrative component of an all-in contract operating fee.</p>
        <h5>A Note on Workovers</h5>
        <p>Determining whether a workover should be considered as capital or as an operating expense for the purpose of overhead calculation has been a regular challenge for joint venture accountants and auditors. There has never been specific guidance on how to treat a workover, so accountants would look at criteria like whether material has just been replaced in kind, whether the useful life of the asset has been extended, and how much money was expended on the project. This isn’t exactly an IFRS-approved guideline to make an opex versus capex decision, but a decision had to be made somewhere.</p>
        <p>PASC 2011 now indicates that a well workover that involves up to fifteen days of rig time per well should be considered Operations and Maintenance, and workovers involving more than fifteen days of rig time should be considered as a Completion. Whether you agree or disagree with this treatment, at least the joint venture accountants now have clear documentation on how overhead should be charged on workover projects.</p>
        <h5>The Details – A Synopsis of the Article III Terms</h5>
        <p>PASC 2011 has afforded companies with a new level of flexibility by presenting two different alternatives for charging overhead to the Joint Account.</p>
        <p>Alternative A: Perhaps the easiest overhead method to administer (and the default overhead method if the election in Clause 302 isn’t filled out), Alternative A quite simply suggests a 2% overhead rate on all capital (except for Exploration, which is suggested at a 5%). On the operating side, a 10% rate is suggested on all operating costs except for property taxes, processing/transportation fees, utilities, and environmental fees, on which 2% is recommended.</p>
        <p>Alternative B: This overhead alternative offers the sliding scale overhead calculation on capital that most of us are familiar with, but with some significant changes. Across any separate type of capital project (Abandonment and Reclamation, Catastrophe, Exploration, Drilling, Completion, Construction and Equipping), the sliding scale overhead has been suggested as 5% of the first $250,000, 3% of the next $250,000, and 1% of the remainder. Whereas earlier versions of PASC required that Drilling and Completion be combined for the purpose of overhead calculation, PASC 2011 allows the Operator to reset the sliding scale for Completion projects. Notwithstanding the above, Alternative B also offers an opportunity to set your own percentage overhead rate for any particular capital project. For Operations and Maintenance, there are a variety of elections to populate that force the Parties to separately contemplate overhead rates for property taxes, processing/transportation fees, utilities, and environmental fees.</p>
        <p>Before forming an opinion on how you feel about these Alternatives, please keep in mind that our current drilling/completion “standard industry practice” (sliding scale 3% on the first $50,000, 2% on the next $100,000 and 1% on the remainder) has been common at least since the Petroleum Accountants Society of Western Canada (PASWC) released its 1969 model accounting procedure. A lot has changed since then. It is rare that a well can be drilled for under $1MM, and with the advent of multi-stage fracs, some well completions are costing millions of dollars. Wells are being drilled faster, and even though the industry standard overhead thresholds have never really been increased, it becomes easy to see how the administrative burden that the Operator carries has increased since 1969.</p>
        <h5>Accounting System and Land System Changes</h5>
        <p>I can sum this point up quite succinctly: There isn’t a single one of your accounting or land system’s current overhead methods that will be valid with any alternative offered in PASC 2011. Being careful to not over-dramatize, adopting the overhead changes suggested in your PASC 2011 Accounting Procedure and making it work in your accounting system is likely just a very simple matter of having your company’s masterfile maintenance representative add some new overhead validation codes – this is fairly easy to do in most accounting systems. However, because of added definitions and additional flexibility to establish different overhead rates for any given activity, I would encourage land system administrators to review the terms of Article III closely to ensure that your land system itself is structured to accommodate that flexibility. Many of the land systems that I’m familiar with are not yet able to do this and may require some patches from the programmers.</p>
        <h5>Closing</h5>
        <p>With some more specific phrasing in Article II, additional and expanded definitions, increased recommended overhead rates and the elimination of “The Grid” that we saw in PASC 1996, even the accounting for overhead in PASC 2011 has seen an overhaul. The PASC pre-amble indicates that they are still contemplating releasing an “information only” overhead grid, but it will no doubt require further deliberation. The added flexibility of the Overhead provision is a great addition and provides companies with a better framework for negotiation at the beginning of a joint venture. I often wince when I see a Non-Operator being charged 10% overhead on millions of dollars of just power, so I would encourage negotiators and JV Representatives or take advantage of this added flexibility. It is impossible to address the eligibility of every type of administrative expenditure (contracted or not), but PASC 2011 has certainly moved us forward by providing clarification on the bigger issues.</p>
        <p><i>All content provided on this blog is for informational purposes only. The content contained herein does not represent the official or unofficial opinion of PASC, CAPL or any other industry association and is based solely on the opinion of the author. The owner of this blog makes no representations as to the accuracy or completeness of any information on this site or found by following any link on this site. The owner will not be liable for any errors or omissions in this information nor for the availability of this information. The owner will not be liable for any losses, injuries, or damages from the display or use of this information.</i></p>
      </>
  },
  {
    slug: '2017-year-in-review',
    title: '2017 Year in Review',
    author: '',
    content:
      <>
        <p>2017 has been a very busy time for the Petroleum Accountants Society of Canada (PASC). This year the society focused heavily on creating value for our members. Our key areas of focus have been updating and ensuring relevancy of publications, education and providing quality luncheons.</p>
        <p>One of the key initiatives for 2017 has been reviewing all publication for relevancy and increasing the rate of publications.  We had member feedback that we were not reacting to changes in industry with relevant publications as fast as members would like so we created a publications committee with the sole focus of reviewing and maintaining publications. The result has been faster more timely publications and a complete reduction of outdated publications.</p>
        <p>In September PASC hosted its annual education day with this year’s theme centering around “Great Expectations”. Education day has been the marquee event for PASC since its inaugural event five years ago and this year was better than ever. The event moved to a new venue this year as the Calgary Petroleum Club was undergoing renovations.  Education day featured a talented roster of industry speakers such as Tim McMillan (CAPP President) who presented on The Canadian Oil &amp; Gas Industry the Challenge of Staying Competitive on The Global Stage and Marty Proctor (CEO of Seven Generations Energy) who presented on Serving Stakeholders.   Education day also had local industry experts that presented on technical accounting topics such as IFRS, Alberta’s carbon levy, acquisitions &amp; divestitures and general knowledge building topics such as domestic LNG, changing E&amp;P landscape and team building. The event was very well attended and had the largest turnout to date. This event would not have been possible without the initial help from COPAS. COPAS provided access to member societies that already had education day that provided guidance and advice on how to create our own education day.</p>
        <p>Luncheons have always been a key component of PASC schedule and this year was no exception.  The topics consisted of emerging issues and trends such as carbon taxes, LNG export, asset retirement obligations, aboriginal relationship building and digitization of the energy industry.  This year PASC partnered with the Petroleum Joint Venture Association (PJVA) to create joint luncheons that benefited members of both societies.  This relationship allowed both organizations to expand their reach and create larger luncheon audiences and allowed for increased networking.</p>
        <p>2017 has been a challenging yet exciting year for PASC and we are looking forward to the opportunities and changes that 2018 brings.</p>
        <p>Cody Austin<br />PASC President</p>
      </>
  }
]